import { useState } from 'react'
import './Configuration.css'

type ConfigSection = 'Application Insights' | 'Business Flows' | 'Access' | 'Security'

const sections: { name: ConfigSection; icon: string; description: string }[] = [
  { name: 'Application Insights', icon: '◔', description: 'Telemetry workspace and query settings' },
  { name: 'Business Flows', icon: '⌘', description: 'Discovery, grouping, and health policies' },
  { name: 'Access', icon: '♙', description: 'Roles, scopes, and user permissions' },
  { name: 'Security', icon: '◇', description: 'Identity, network, and data protections' },
]

function Toggle({ checked, onChange, label }: { checked: boolean; onChange: () => void; label: string }) {
  return <button type="button" className={`config-toggle ${checked ? 'enabled' : ''}`} onClick={onChange} role="switch" aria-checked={checked} aria-label={label}><span /></button>
}

export default function Configuration() {
  const [active, setActive] = useState<ConfigSection>('Application Insights')
  const [saved, setSaved] = useState(false)
  const [sampling, setSampling] = useState(true)
  const [autoDiscovery, setAutoDiscovery] = useState(true)
  const [alerts, setAlerts] = useState(true)
  const [privateAccess, setPrivateAccess] = useState(false)
  const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 2200) }

  return <div className="configuration-workspace">
    <aside className="configuration-menu"><div><h2>Configuration</h2><p>Manage data sources, policies, and hub access.</p></div><nav aria-label="Configuration sections">{sections.map((section) => <button key={section.name} className={active === section.name ? 'active' : ''} onClick={() => setActive(section.name)}><span>{section.icon}</span><div><strong>{section.name}</strong><small>{section.description}</small></div><b>›</b></button>)}</nav><div className="config-note"><span>ⓘ</span><p><strong>Prototype configuration</strong>Changes are simulated locally and do not update Azure resources.</p></div></aside>
    <section className="configuration-content">
      <header><div><span>HUB CONFIGURATION</span><h2>{active}</h2><p>{sections.find((section) => section.name === active)?.description}</p></div><div className="config-state"><i /> Configuration healthy</div></header>

      {active === 'Application Insights' && <div className="configuration-body">
        <section className="config-card"><div className="config-card-head"><div><h3>Application Insights connection</h3><p>Select the telemetry resource used for cross-Logic-App analytics.</p></div><span className="connected-pill"><i />Connected</span></div><div className="config-form-grid"><label>Azure subscription<select defaultValue="Contoso Platform"><option>Contoso Platform</option><option>Shared Integration</option><option>Contoso Commerce</option></select></label><label>Resource group<select defaultValue="rg-observability-prod"><option>rg-observability-prod</option><option>rg-integration-prod</option></select></label><label>Application Insights resource<select defaultValue="appi-integration-hub"><option>appi-integration-hub</option><option>appi-commerce-prod</option></select></label><label>Log Analytics workspace<select defaultValue="log-integration-prod"><option>log-integration-prod</option><option>log-platform-shared</option></select></label></div><div className="resource-summary"><div className="resource-mark">AI</div><div><strong>appi-integration-hub</strong><span>East US 2 · Workspace-based · 30-day retention</span></div><button>Test connection</button></div></section>
        <section className="config-card"><div className="config-card-head"><div><h3>Telemetry settings</h3><p>Control how run and action telemetry is queried for the hub.</p></div></div><div className="setting-list"><div><span><strong>Adaptive sampling</strong><small>Reduce telemetry volume while preserving representative data.</small></span><Toggle checked={sampling} onChange={() => setSampling(!sampling)} label="Adaptive sampling" /></div><div><span><strong>Run history window</strong><small>Default period used by analytics and run details.</small></span><select defaultValue="24 hours"><option>24 hours</option><option>7 days</option><option>30 days</option></select></div><div><span><strong>Query refresh interval</strong><small>How often the prototype refreshes aggregated metrics.</small></span><select defaultValue="5 minutes"><option>1 minute</option><option>5 minutes</option><option>15 minutes</option></select></div></div></section>
      </div>}

      {active === 'Business Flows' && <div className="configuration-body"><section className="config-card"><div className="config-card-head"><div><h3>Business Flow configuration</h3><p>Set grouping behavior and health calculation defaults.</p></div></div><div className="setting-list"><div><span><strong>Automatic dependency discovery</strong><small>Find connectors and dependent systems from selected workflows.</small></span><Toggle checked={autoDiscovery} onChange={() => setAutoDiscovery(!autoDiscovery)} label="Automatic dependency discovery" /></div><div><span><strong>Flow health calculation</strong><small>Determine how workflow health rolls up to the business flow.</small></span><select defaultValue="Worst workflow state"><option>Worst workflow state</option><option>Weighted success rate</option><option>Custom thresholds</option></select></div><div><span><strong>Default owner</strong><small>Team assigned to newly created business flows.</small></span><input defaultValue="Integration Operations" /></div></div></section><section className="config-card"><div className="config-card-head"><div><h3>Health thresholds</h3><p>Shared thresholds for customer-defined groups.</p></div></div><div className="threshold-grid"><label>Healthy success rate<input defaultValue="≥ 99%" /></label><label>Warning success rate<input defaultValue="95–98.9%" /></label><label>Critical success rate<input defaultValue="< 95%" /></label><label>Latency warning<input defaultValue="> 5 seconds" /></label></div></section></div>}

      {active === 'Access' && <div className="configuration-body"><section className="config-card"><div className="config-card-head"><div><h3>Access configuration</h3><p>Define prototype roles and their permitted hub capabilities.</p></div><button className="outline-button">＋ Add assignment</button></div><div className="role-table"><div className="role-row header"><span>Principal</span><span>Role</span><span>Scope</span><span>Status</span></div><div className="role-row"><span><b>IO</b><strong>Integration Operations</strong></span><span>Hub administrator</span><span>All subscriptions</span><em>Active</em></div><div className="role-row"><span><b>CO</b><strong>Commerce Observers</strong></span><span>Monitoring reader</span><span>Contoso Commerce</span><em>Active</em></div><div className="role-row"><span><b>SC</b><strong>Supply Chain Team</strong></span><span>Business Flow editor</span><span>Supply Chain</span><em>Active</em></div></div></section><section className="config-card"><div className="config-card-head"><div><h3>Default access policy</h3><p>New users receive no access until a role is assigned.</p></div></div><div className="access-callout"><span>✓</span><p><strong>Least-privilege defaults enabled</strong>Role assignments are scoped to the minimum required subscriptions and capabilities.</p></div></section></div>}

      {active === 'Security' && <div className="configuration-body"><section className="config-card"><div className="config-card-head"><div><h3>Security configuration</h3><p>Configure identity, network access, and alerting posture.</p></div><span className="security-score">92% secure score</span></div><div className="setting-list"><div><span><strong>Microsoft Entra ID authentication</strong><small>Require organizational identity for all hub access.</small></span><span className="locked-setting">Required</span></div><div><span><strong>Private network access only</strong><small>Restrict the hub to approved private network endpoints.</small></span><Toggle checked={privateAccess} onChange={() => setPrivateAccess(!privateAccess)} label="Private network access" /></div><div><span><strong>Security alert notifications</strong><small>Notify administrators about suspicious access and changes.</small></span><Toggle checked={alerts} onChange={() => setAlerts(!alerts)} label="Security alerts" /></div><div><span><strong>Configuration audit retention</strong><small>Retain configuration activity for compliance review.</small></span><select defaultValue="180 days"><option>90 days</option><option>180 days</option><option>365 days</option></select></div></div></section><section className="config-card"><div className="config-card-head"><div><h3>Security recommendations</h3><p>Actions that improve the current prototype posture.</p></div></div><div className="recommendation"><span>!</span><div><strong>Enable private network access</strong><p>Limit access to the operations hub through private connectivity.</p></div><button onClick={() => setPrivateAccess(true)}>Enable</button></div></section></div>}

      <footer><span>{saved ? '✓ Configuration saved locally' : 'Unsaved changes are local to this prototype'}</span><div><button className="config-cancel">Discard</button><button className="config-save" onClick={save}>Save configuration</button></div></footer>
    </section>
  </div>
}
